jms_i18n_routing:
    default_locale: "%locale%"
    locales: "%locales%"
    strategy: prefix_except_default

jms_translation:
  configs:
    routes:
      dirs: ['%kernel.root_dir%', '%kernel.root_dir%/../src']
      output_dir: "%kernel.root_dir%/Resources/translations"
      output_format: yml
      excluded_dirs: [Tests]
      extractors: [jms_i18n_routing]
      domain: routes # run php bin/console translation:extract en --config=routes --output-format=xliff
    app:
      dirs: ['%kernel.root_dir%', '%kernel.root_dir%/../src']
      output_dir: "%kernel.root_dir%/Resources/translations"
      output_format: yml