########################################################### Config
sonata_admin:
   title:      Un-Mute Admin
   title_logo: admin/images/logo.png
   templates:
       layout: "::sonata_admin_layout.html.twig"
   options:
       html5_validate: true
       use_select2: true
   dashboard:
       blocks:
           -
             position: left
             type: sonata.admin.block.admin_list
             settings:
               groups: [app.admin.group.user, app.admin.group.contact, app.admin.group.content]
           -
             position: right
             type: sonata.admin.block.admin_list
             settings:
               groups: [app.admin.group.events, app.admin.group.orders]

       groups:
           app.admin.group.user:
               label: app.admin.group.user
               label_catalogue: SonataAdminBundle
               items:
                   - AppBundle\Admin\UserAdmin
                   - AppBundle\Admin\ArtistAdmin
           app.admin.group.contact:
                label_catalogue: SonataAdminBundle
                items:
                  - AppBundle\Admin\SuggestionBoxAdmin
                  - AppBundle\Admin\SuggestionTypeEnumAdmin
                  - AppBundle\Admin\VIPInscriptionAdmin
                  - AppBundle\Admin\PropositionContractArtistAdmin
           app.admin.group.content:
                label: app.admin.group.content
                label_catalogue: SonataAdminBundle
                items:
                  - AppBundle\Admin\GenreAdmin
                  - AppBundle\Admin\ProvinceAdmin
                  #- AppBundle\Admin\PartnerAdmin
                  - AppBundle\Admin\ContactPersonAdmin
                  - AppBundle\Admin\HallAdmin
                  - AppBundle\Admin\CategoryAdmin
                  - AppBundle\Admin\LevelAdmin
           app.admin.group.events:
               label: app.admin.group.events
               label_catalogue: SonataAdminBundle
               items:
                   - AppBundle\Admin\ContractArtistAdmin
                   - AppBundle\Admin\StepAdmin
                   - AppBundle\Admin\CounterPartAdmin

           app.admin.group.orders:
               label: app.admin.group.orders
               label_catalogue: SonataAdminBundle
               items:
                   - AppBundle\Admin\ContractFanAdmin
                   - AppBundle\Admin\PaymentAdmin
               roles: [ROLE_PAYMENTS_ADMIN]

sonata_block:
     default_contexts: [cms]
     blocks:
         # enable the SonataAdminBundle block
         sonata.admin.block.admin_list:
            contexts: [admin]
         sonata.admin.block.stats:
            contexts:   [admin]
         sonata_translation.block.locale_switcher:
            contexts: [admin]

sonata_translation:
   locales: [fr, en]
   default_locale: "%locale%"
   knplabs:
     enabled: true

########################################################### Services
services:
    # Defaults, which will allow Symfony to use autowiring and autoconfiguring
    _defaults:
        autowire: true # automatically injects dependencies in the
        autoconfigure: true # automatically registers services as commands, event subscribers, etc.
        public: true

    AppBundle\Admin\SuggestionBoxAdmin:
        arguments: [~, AppBundle\Entity\SuggestionBox, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.suggestionBox }
        public: true


    AppBundle\Admin\VIPInscriptionAdmin:
        arguments: [~, AppBundle\Entity\VIPInscription, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.VIPInscription }
        public: true

    AppBundle\Admin\UserAdmin:
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.user }
        public: true

    AppBundle\Admin\StepAdmin:
        arguments: [~, AppBundle\Entity\Step, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.step }
        public: true

    AppBundle\Admin\GenreAdmin:
        arguments: [~, AppBundle\Entity\Genre, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.genre }
        public: true

    AppBundle\Admin\PartnerAdmin:
        arguments: [~, AppBundle\Entity\Partner, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.partner }
        public: true

    AppBundle\Admin\ArtistAdmin:
        arguments: [~, AppBundle\Entity\Artist, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.artist }
        public: true

    AppBundle\Admin\CartAdmin:
        arguments: [~, AppBundle\Entity\Cart, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.cart }
        public: true

    AppBundle\Admin\ContractArtistAdmin:
        arguments: [~, AppBundle\Entity\ContractArtist, AppBundle:ContractArtistAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.contractartist }
        public: true

    AppBundle\Admin\ContractArtistArtistAdmin:
        arguments: [~, AppBundle\Entity\ContractArtist_Artist, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.contractartistartist }
        public: true

    AppBundle\Admin\ContractFanAdmin:
        arguments: [~, AppBundle\Entity\ContractFan, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.contractfan }
        public: true

    AppBundle\Admin\PaymentAdmin:
        arguments: [~, AppBundle\Entity\Payment, AppBundle:PaymentAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.payment }
        public: true

    AppBundle\Admin\PurchaseAdmin:
        arguments: [~, AppBundle\Entity\Purchase, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.purchase }
        public: true

    AppBundle\Admin\PhaseAdmin:
        arguments: [~, AppBundle\Entity\Phase, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.phase }
        public: true

    AppBundle\Admin\ConcertPossibilityAdmin:
        arguments: [~, AppBundle\Entity\ConcertPossibility, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.concertpossibility }
        public: true

    AppBundle\Admin\HallAdmin:
        arguments: [~, AppBundle\Entity\Hall, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.hall }
        calls:
            - [ setTemplate, [edit, AppBundle:Admin/Hall:edit.html.twig]]
        public: true

    AppBundle\Admin\ContactPersonAdmin:
        arguments: [~, AppBundle\Entity\ContactPerson, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.contactperson }
        public: true

    AppBundle\Admin\AddressAdmin:
        arguments: [~, AppBundle\Entity\Address, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.address }
        public: true

    AppBundle\Admin\CounterPartAdmin:
        arguments: [~, AppBundle\Entity\CounterPart, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.counterpart }
        public: true

    AppBundle\Admin\ProvinceAdmin:
        arguments: [~, AppBundle\Entity\Province, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.province }
        public: true

    AppBundle\Admin\PartnerContactPersonAdmin:
        arguments: [~, AppBundle\Entity\Partner_ContactPerson, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.partnercontactperson }
        public: true

    AppBundle\Admin\SuggestionTypeEnumAdmin:
        arguments: [~, AppBundle\Entity\SuggestionTypeEnum, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: app.admin.suggestiontypeenum }
        public: true