imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: c_azine.yml }
    - { resource: c_sonata.yml }
    - { resource: c_doctrine.yml }
    - { resource: c_fos.yml }
    - { resource: c_jms.yml }
    - { resource: c_bundles.yml }
    - { resource: "@XBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    mailer_from_name: "no-reply"
    locales: [fr]
    facebook_page_url: https://www.facebook.com/UnMuteasbl/
    instagram_page_url: https://www.instagram.com/unmutelive/
    expanded_locales: {fr: fr_FR, en: en_US, nl: nl_NL}
    maps_api_key: AIzaSyAjWpC8y-sy07JHTBAexmdCT4cQaC84y8U

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
        enabled: false
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: "%session.name%"
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets:
      version: "%assets_version%"
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
      - '@SonataFormatter/Form/formatter.html.twig'
      - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
      - ':Form:jquery.collection.html.twig'
      - ':Form:bootstrap_4_horizontal_layout.html.twig'
    globals:
      stripe_api_public: "%stripe_api_public%"
      facebook_api_id: "%facebook_api_id%"
      enabled_locales: "%locales%"
      facebook_page_url: "%facebook_page_url%"
      instagram_page_url: "%instagram_page_url%"
      expanded_locales: "%expanded_locales%"
      maps_api_key: "%maps_api_key%"

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    spool:      { type: memory }
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    auth_mode:  "%mailer_auth_mode%"
    encryption: "%mailer_encryption%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"

ivory_ck_editor:
  plugins:
    bbcode:
      path: '/groopymusic/web/bundles/app/ckeditor/bbcode/'
      filename: 'plugin.js'
  configs:
    my_config:
      toolbar: 'full'
    bbcode:
      toolbar: [[ 'Bold','Italic','Underline','Link' ]]
      uiColor: "#FCFCFC"
      extraPlugins: 'bbcode'
  default_config: my_config

fm_bbcode:
    filter_sets:
        my_default_filter:
          strict: false # if you want to parse attr values without quotes
          locale: fr
          xhtml: true
          filters: [ default, url ]