imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: azine.yml }
    - { resource: sonata.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    email_from_address: no-reply@un-mute.be
    email_from_name: Un-Mute

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
            enabled: true
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: "%session.name%"
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
      - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
      - 'SonataMediaBundle:Form:media_widgets.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
          json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
          default:
            auto_mapping: true
            naming_strategy: doctrine.orm.naming_strategy.underscore
            mappings:
              SonataMediaBundle: ~
              ApplicationSonataMediaBundle: ~


knp_doctrine_behaviors:
  translatable: true

a2lix_translation_form:
  locale_provider: default
  locales: [fr, en]
  default_locale : "%locale%"
  required_locales: ["%locale%"]
  templating: "A2lixTranslationFormBundle::default.html.twig"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: file, path: "%kernel.root_dir%/spool" }
    auth_mode:  "%mailer_auth_mode%"
    port:       "%mailer_port%"

# friendsofsymfony/userbundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        mailer: azine_email.default.template_twig_swift_mailer
    registration:
        form:
            type: AppBundle\Form\RegistrationType
        confirmation:
            enabled: true
            template: AppBundle:Mail:registration_confirmation.txt.twig
    profile:
        form:
          type: AppBundle\Form\ProfileType
    from_email:
        address:        no-reply@un-mute.be
        sender_name:    'Un-Mute'
    resetting:
        email:
            template:  AppBundle:Mail:password_resetting.txt.twig

# Assetic config
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    node: "%path_to_node%"
    filters:
        cssrewrite: ~
        jsqueeze: ~
#        uglifyjs2:
#            bin: "%path_to_uglifyjs%"
#        uglifycss:
#            bin: "%path_to_uglifycss%"
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
    assets:
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js"

jms_i18n_routing:
    default_locale: "%locale%"
    locales: [fr, en]
    strategy: prefix_except_default

jms_translation:
  configs:
    routes:
      dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
      output_dir: "%kernel.root_dir%/Resources/translations"
      output_format: xliff
      excluded_dirs: [Tests]
      extractors: [jms_i18n_routing]
      domain: routes # run php bin/console translation:extract en --config=routes --output-format=xliff

tetranz_select2_entity:
    minimum_input_length: 0
    page_limit: 8
    allow_clear: false
    delay: 500
    language: "%locale%"
    cache: false
    cache_timeout: 0
    scroll: false

oneup_uploader:
    mappings:
        artist_gallery:
            frontend: dropzone # or any uploader you use in the frontend
            namer: AppBundle\Services\DropzoneUploadNamer