imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: [fr] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
            enabled: true
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
      - 'TetranzSelect2EntityBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                is_bundle: false

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
          translatable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: file, path: "%kernel.root_dir%/spool" }
    auth_mode:  "%mailer_auth_mode%"
    port:       "%mailer_port%"

# friendsofsymfony/userbundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        mailer: azine_email.default.template_twig_swift_mailer
    registration:
        form:
            type: AppBundle\Form\RegistrationType
        confirmation:
            enabled: true
            template: AppBundle:Mail:registration_confirmation.txt.twig
    profile:
        form:
          type: AppBundle\Form\ProfileType
    from_email:
        address:        no-reply@un-mute.be
        sender_name:    'Un-Mute'
    resetting:
        email:
            template:  AppBundle:Mail:password_resetting.txt.twig

azine_email:
    # the class of your implementation of the RecipientInterface
    recipient_class:      AppBundle\Entity\User # Required

    # the fieldname of the boolean field on the recipient class indicating, that a newsletter should be sent or not
    recipient_newsletter_field:  newsletter

    # the service-id of your implementation of the notifier service to be used
    notifier_service:     email.notifier_service

    # the service-id of your implementation of the template provider service to be used
    template_provider:    email.template_provider # Required

    # the service-id of the implementation of the RecipientProviderInterface to be used
    recipient_provider:   azine_email.default.recipient_provider

    # the service-id of the mailer service to be used
    template_twig_swift_mailer:  azine_email.default.template_twig_swift_mailer

    no_reply:             # Required
        # the no-reply email-address
        email:                no-reply@un-mute.be # Required
        # the name to appear with the 'no-reply'-address.
        name:                 'Un-Mute' # Required

    # absolute path to the image-folder containing the images used in your templates.
    image_dir:            '%kernel.root_dir%/../web/mail/images/'

    # list of folders from which images are allowed to be embeded into emails
    allowed_images_folders:  []

    # newsletter configuration
    # newsletter:
        # number of days between newsletters
    #    interval:             '14'
        # time of the day, when newsletters should be sent, 24h-format => e.g. 23:59
    #   send_time:            '10:00'

    # templates configuration
    templates:
        # wrapper template id (without ending) for the newsletter
        newsletter:           'AzineEmailBundle::newsletterEmailLayout'
        # wrapper template id (without ending) for notifications
        notifications:        'AzineEmailBundle::notificationsEmailLayout'
        # template id (without ending) for notification content items
        content_item:         'AzineEmailBundle:contentItem:message'

    # the parameters for link tracking. see https://support.google.com/analytics/answer/1033867 for more infos.
    tracking_params_campaign_name:    utm_campaign #defaluts to utm_name, piwik and google analytics both understand these parameters
    tracking_params_campaign_term:    utm_term     #defaluts to utm_term, piwik and google analytics both understand these parameters
    tracking_params_campaign_content: utm_content  #defaluts to utm_content, piwik and google analytics both understand these parameters
    tracking_params_campaign_medium:  utm_medium   #defaluts to utm_medium, piwik and google analytics both understand these parameters
    tracking_params_campaign_source:  utm_source   #defaluts to utm_source, piwik and google analytics both understand these parameters

    # See the chapter further below for more information
    email_open_tracking_url:  null

    # Defaults to the AzineEmailOpenTrackingCodeBuilder. Depending on the email_open_tracking_url it will create tracking images for piwik or google analytics.
    email_open_tracking_code_builder:  azine.email.open.tracking.code.builder.ga.or.piwik

    # number of days that emails should be available in web-view
    web_view_retention:   90

    # the service-id of your implementation of the web view service to be used
    web_view_service:     email.web_view_service


# Assetic config
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    node: "%path_to_node%"
    filters:
        cssrewrite: ~
        jsqueeze: ~
#        uglifyjs2:
#            bin: "%path_to_uglifyjs%"
#        uglifycss:
#            bin: "%path_to_uglifycss%"
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
    assets:
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js"

# Sonata Admin
sonata_admin:
    title:      Un-Mute Admin
    title_logo: admin/images/logo.png
    templates:
        layout: "::sonata_admin_layout.html.twig"
    options:
        html5_validate: true
        use_select2: true
    dashboard:
        blocks:
            -
              position: left
              type: sonata.admin.block.admin_list
              settings:
                groups: [app.admin.group.user, app.admin.group.evolution, app.admin.group.content]
            -
              position: right
              type: sonata.admin.block.admin_list
              settings:
                groups: [app.admin.group.crowdfunding, app.admin.group.special, app.admin.group.payment]

        groups:
            app.admin.group.user:
                label: app.admin.group.user
                label_catalogue: SonataAdminBundle
                items:
                    - app.admin.user
                    - app.admin.artist
                    - app.admin.suggestionbox
            app.admin.group.evolution:
                label: app.admin.group.evolution
                label_catalogue: SonataAdminBundle
                items:
                    - app.admin.phase
                    - app.admin.step
            app.admin.group.content:
                label: app.admin.group.content
                label_catalogue: SonataAdminBundle
                items:
                    - app.admin.genre
                    - app.admin.partner
                   # - app.admin.hall
            app.admin.group.crowdfunding:
                label: app.admin.group.crowdfunding
                label_catalogue: SonataAdminBundle
                items:
                    - app.admin.contractartist
                    - app.admin.contractfan
                    - app.admin.cart
            app.admin.group.special:
                label: app.admin.group.special
                label_catalogue: SonataAdminBundle
                items:
                    - app.admin.specialadvantage
                    - app.admin.specialpurchase
            app.admin.group.payment:
                label: app.admin.group.payment
                label_catalogue: SonataAdminBundle
                items:
                    - app.admin.payment
                roles: [ROLE_PAYMENTS_ADMIN]

sonata_block:
      default_contexts: [cms]
      blocks:
          # enable the SonataAdminBundle block
          sonata.admin.block.admin_list:
              contexts: [admin]
          sonata.admin.block.stats:
              contexts:   [admin]

sonata_translation:
    locales: [fr, en]
    default_locale: fr
    gedmo:
        enabled: true

jms_i18n_routing:
    default_locale: fr
    locales: [fr, en]
    strategy: prefix_except_default

jms_translation:
  configs:
    routes:
      dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
      output_dir: "%kernel.root_dir%/Resources/translations"
      output_format: xliff
      excluded_dirs: [Tests]
      extractors: [jms_i18n_routing]
      domain: routes # run php bin/console translation:extract en --config=routes --output-format=xliff

tetranz_select2_entity:
    minimum_input_length: 0
    page_limit: 8
    allow_clear: false
    delay: 500
    language: fr
    cache: false
    cache_timeout: 0
    scroll: false
