x_payment:
    path:  /payment/
    defaults:
        _controller: XBundle:Payment:payment

x_projects_view:
    path:   /projects/{id}
    defaults:
        _controller: XBundle:Projects:view
        
    requirements:
        id: \d+
        
x_projects_add:
    path:   /projects/add
    defaults:
        _controller: XBundle:Projects:add
        
x_projects_home:
    path:   /projects
    defaults:
        _controller: XBundle:Projects:index

x_projects_delete:
    path:   /projects/delete/{id}
    defaults:
        _controller: XBundle:Projects:delete
    requirements:
        id: \d+
        
x_projects_edit:
    path:   /projects/edit/{id}
    defaults:
        _controller: XBundle:Projects:edit
        
    requirements:
        id: \d+
        
x_user_viewProjects:
    path:   /mes-projets
    defaults:
        _controller: XBundle:User:viewProjects

x_ajax_post_order:
    path:   /api/submit-order-coordinates
    defaults:
        _controller: XBundle:Payment:orderAjax
        
x_cart_payment_pending:
    path:   /payment/pending
    defaults:
        _controller: XBundle:Payment:paymentPending
    