x_home:
    path:  /
    defaults:
        _controller: XBundle:Projects:home
x_payment:
    path:  /payment/{code}
    defaults:
        _controller: XBundle:Payment:payment

x_projects_view:
    path:   /projects/{id}
    defaults:
        _controller: XBundle:Projects:view
        
    requirements:
        id: \d+
        
x_projects_add:
    path:   /projects/add
    defaults:
        _controller: XBundle:Projects:add

x_product_add:
    path:   mes-projets/product/add/{projectId}
    defaults:
        _controller: XBundle:Product:add

    requirements:
        projectId: \d*
        
x_projects_home:
    path:   /projects
    defaults:
        _controller: XBundle:Projects:index

x_projects_delete:
    path:   /projects/delete/{id}
    defaults:
        _controller: XBundle:Projects:delete
    requirements:
        id: \d+
        
x_projects_edit:
    path:   /projects/edit/{id}
    defaults:
        _controller: XBundle:Projects:edit
        
    requirements:
        id: \d+

x_projects_ajax_points:
    path:  /projects/ajax-points
    defaults:
        _controller: XBundle:Projects:ajax
    methods: [post]
        
x_user_viewProjects:
    path:   /mes-projets
    defaults:
        _controller: XBundle:User:viewProjects

x_ajax_post_order:
    path:   /api/submit-order-coordinates/{code}
    defaults:
        _controller: XBundle:Payment:orderAjax
        
x_cart_payment_pending:
    path:   /payment/pending/{code}
    defaults:
        _controller: XBundle:Payment:paymentPending

x_payment_success:
    path:   /payment/success/{code}
    defaults:
        _controller: XBundle:Payment:paymentSuccess

x_ajax_post_order_product:
    path:  /api/submit-order-product-coordinates/{id}
    defaults:
        _controller: XBundle:Projects:orderProductAjax
    requirements:
        id: \d+
    