# app/config/routing.yml

user_registration:
  path: /register
  defaults: { _controller: AppBundle:Security:register }

user_artist_registration:
    path:  /register/artist
    defaults: { _controller: AppBundle:Security:registerArtist }

user_fan_registration:
    path:  /register/fan
    defaults: { _controller: AppBundle:Security:registerFan }

fos_user_registration_check_email:
  path: /check-email
  methods: GET
  defaults: { _controller: FOSUserBundle:Registration:checkEmail}

fos_user_registration_confirm:
  path: /confirm/{token}
  methods: GET
  defaults: { _controller: FOSUserBundle:Registration:confirm}

fos_user_registration_confirmed:
  path: /confirmed
  methods: GET
  defaults: { _controller: FOSUserBundle:Registration:confirmed}

azine_email_bundle:
    resource: "@AzineEmailBundle/Resources/config/routing.yml"
    prefix: /mail/

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

app_sec:
    resource: "@AppBundle/Controller/SecurityController.php"
    type:     annotation
    prefix: /secure

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
    prefix: /secure

app_fan:
    resource: "@AppBundle/Controller/FanController.php"
    type:     annotation
    prefix: /secure/fan

app_artist:
    resource: "@AppBundle/Controller/ArtistController.php"
    type:     annotation
    prefix: /secure/artist

app_public:
    resource: "@AppBundle/Controller/PublicController.php"
    type:     annotation

app_public_boite:
    path:  /boite
    defaults: { _controller: AppBundle:Public:boite }