app_public:
    resource: "@AppBundle/Controller/PublicController.php"
    type:     annotation

app_temp:
    resource: "@AppBundle/Controller/TempShitController.php"
    type: annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
    prefix: /

app_artist:
    resource: "@AppBundle/Controller/ArtistController.php"
    type:     annotation
    prefix: /artist/{id}

app_payment:
    resource: "@AppBundle/Controller/PaymentController.php"
    type:     annotation
    prefix: /secure-zone

app_ticketing:
    resource: "@AppBundle/Controller/TicketingController.php"
    type:     annotation
    prefix:   /ticketing

admin_ajax:
    resource: "@AppBundle/Controller/AdminAjaxController.php"
    type:     annotation
    prefix: /admin/ajax/