app_public:
    resource: "@AppBundle/Controller/PublicController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
    prefix: /secure

app_fan:
    resource: "@AppBundle/Controller/FanController.php"
    type:     annotation
    prefix: /secure/fan

app_artist:
    resource: "@AppBundle/Controller/ArtistController.php"
    type:     annotation
    prefix: /secure/artist/{id}

app_payment:
    resource: "@AppBundle/Controller/PaymentController.php"
    type:     annotation
    prefix: /secure/payment-zone
